service:
  name: typography-test-app-backend

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  profile: satu-personal-cli
  region: eu-central-1
  environment:
    S3_DATA_BUCKET: "${self:custom.s3-data-bucket-name}"

custom:
  s3-data-bucket-name: "typography-test-app-scraped-data"

iamRoleStatements:
- Effect: "Allow"
  Action:
    - "s3:ListBucket"
    - "s3:GetObject"
    - "s3:PutObject"
  Resource: "arn:aws:s3:::${self:custom.s3-data-bucket}/*"

functions:
  sites:
    handler: handlers/sites.getSites
    events:
      - http:
          method: get
          path: sites

Resources:
  S3OperationsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.s3-data-bucket}